### ISSUE TITLE
Collection for Events?

### ISSUE THREAD

**Issue by tduberne** [matsim-org/jekyll-website#18]
Given how we are moving away from confluence, I am wondering whether it would make sense to create a collection (in the jekyll sense) for (public) events? I would then put the registration information for the next user meeting there, rather than on confluence.

We could then see how we can link to/migrate the content from confluence.

I will move forward before Christmas on this, if no one opposes.

**Comment by tduberne** [comment]
Regarding linking to past events: we already have a page for conferences: https://matsim.org/conferences/

I would basically keep the information available there already (and keep the same URL) and add an automatically generated list of events above it.

**Comment by kainagel** [comment]
Fine with me, thanks a lot.

**Comment by billyc** [comment]
Makes perfect sense to me! Thanks, Thibaut!

Let me know if you need any help with the Jekyll bits, I know it pretty well.
..b

**Comment by tduberne** [comment]
Done with #19 

@billyc, if you believe anything can be done better, feel free to act!
