### ISSUE TITLE
News on the website are not getting update

### ISSUE THREAD

**Issue by balacmi** [matsim-org/jekyll-website#68]
It seems that new news posts are not shown on the website anymore. Not sure what needs to be done.

**Comment by mrieser** [comment]
Thanks for bringing the issue up. It should be fixed now.

Some background info: Previously, the MATSim build server at VSP was publicly available and got push information from GitHub when a commit happened, triggering a refresh of the website. We recently changed the setup such that the build server is no longer publicly available, not realizing that this breaks the GitHub workflow. I've now configured the build server to check every 15minutes for an update and refresh the website accordingly.
